///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class HeadlinesModelArticlesSource {
/*
{
  "id": "the-washington-post",
  "name": "The Washington Post"
} 
*/

  String? id;
  String? name;

  HeadlinesModelArticlesSource({
    this.id,
    this.name,
  });
  HeadlinesModelArticlesSource.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}

class HeadlinesModelArticles {
/*
{
  "source": {
    "id": "the-washington-post",
    "name": "The Washington Post"
  },
  "author": "Bryan Pietsch, Annabelle Timsit",
  "title": "Ukraine live briefing: Zelensky vows response after Chernihiv strike kills 7; drone strikes in Russia - The Washington Post",
  "description": "The attack on a theater in Chernihiv, some 80 miles north of Kyiv, left at least 7 dead and injured more than 140 people.",
  "url": "https://www.washingtonpost.com/world/2023/08/20/russia-ukraine-war-news/",
  "urlToImage": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/ORCNCLYHZDCUZSB4AZJTOEF76A_size-normalized.jpg&w=1440",
  "publishedAt": "2023-08-20T08:40:10Z",
  "content": "Ukrainian President Volodymyr Zelensky said that the military would respond tangibly to an attack on the northern city of Chernihiv, which killed at least seven people, including a 6-year-old child. … [+5429 chars]"
} 
*/

  HeadlinesModelArticlesSource? source;
  String? author;
  String? title;
  String? description;
  String? url;
  String? urlToImage;
  String? publishedAt;
  String? content;

  HeadlinesModelArticles({
    this.source,
    this.author,
    this.title,
    this.description,
    this.url,
    this.urlToImage,
    this.publishedAt,
    this.content,
  });
  HeadlinesModelArticles.fromJson(Map<String, dynamic> json) {
    source = (json['source'] != null) ? HeadlinesModelArticlesSource.fromJson(json['source']) : null;
    author = json['author']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    url = json['url']?.toString();
    urlToImage = json['urlToImage']?.toString();
    publishedAt = json['publishedAt']?.toString();
    content = json['content']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (source != null) {
      data['source'] = source!.toJson();
    }
    data['author'] = author;
    data['title'] = title;
    data['description'] = description;
    data['url'] = url;
    data['urlToImage'] = urlToImage;
    data['publishedAt'] = publishedAt;
    data['content'] = content;
    return data;
  }
}

class HeadlinesModel {
/*
{
  "status": "ok",
  "totalResults": 38,
  "articles": [
    {
      "source": {
        "id": "the-washington-post",
        "name": "The Washington Post"
      },
      "author": "Bryan Pietsch, Annabelle Timsit",
      "title": "Ukraine live briefing: Zelensky vows response after Chernihiv strike kills 7; drone strikes in Russia - The Washington Post",
      "description": "The attack on a theater in Chernihiv, some 80 miles north of Kyiv, left at least 7 dead and injured more than 140 people.",
      "url": "https://www.washingtonpost.com/world/2023/08/20/russia-ukraine-war-news/",
      "urlToImage": "https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/ORCNCLYHZDCUZSB4AZJTOEF76A_size-normalized.jpg&w=1440",
      "publishedAt": "2023-08-20T08:40:10Z",
      "content": "Ukrainian President Volodymyr Zelensky said that the military would respond tangibly to an attack on the northern city of Chernihiv, which killed at least seven people, including a 6-year-old child. … [+5429 chars]"
    }
  ]
} 
*/

  String? status;
  int? totalResults;
  List<HeadlinesModelArticles?>? articles;

  HeadlinesModel({
    this.status,
    this.totalResults,
    this.articles,
  });
  HeadlinesModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    totalResults = json['totalResults']?.toInt();
    if (json['articles'] != null) {
      final v = json['articles'];
      final arr0 = <HeadlinesModelArticles>[];
      v.forEach((v) {
        arr0.add(HeadlinesModelArticles.fromJson(v));
      });
      articles = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['totalResults'] = totalResults;
    if (articles != null) {
      final v = articles;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['articles'] = arr0;
    }
    return data;
  }
}
